server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
      #        - id: music-service
      #          uri: lb://MUSIC-SERVICE
      #          predicates:
      #            - Path=/music/**
      discovery:
        locator:
          enabled: true # Enable service discovery for dynamic routing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/