server:
  port: 8888

spring:
  application:
    name: config-repo

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Music-Management-Web-Application/music-mgmt-config-repo
          clone-on-start: true
